Update leaflet-image.js
mapbox/leaflet-image pull request #86
Opened 2016-09-13 10:47 UTC by petttro

Added support of L.esri.DynamicMapLayer in leaflet-image.

2016-09-13 12:30 UTC, tmcw commented
Have you tested this code with just Leaflet? The unguarded reference to `L.esri.dynamicMapLayer` will likely cause a crash, since `L.esri` will be undefined in non-esri environments.

2016-09-13 12:37 UTC, petttro commented
Yes, you right, I haven't tested this. It is not working without reference to esri-leaflet.
I'll add validation for this case.

2016-09-19 00:45 UTC, tmcw commented on leaflet-image.js
> +    map.eachLayer(drawEsriDynamicLayer);
This code should be included in index.js, not leaflet-image.js: leaflet-image.js is a generated file.

2016-09-19 00:45 UTC, tmcw requested changes

2016-09-19 12:55 UTC, petttro commented on leaflet-image.js
> +    map.eachLayer(drawEsriDynamicLayer);
Sorry. 
I have moved changes to index.js and also have added check for L.esri is defined.

2016-09-19 12:55 UTC, petttro commented on leaflet-image.js
> +    map.eachLayer(drawEsriDynamicLayer);
https://github.com/petttro/leaflet-image/blob/gh-pages/index.js

2016-09-19 12:57 UTC, tmcw commented
👍

2016-09-19 12:57 UTC, merged

2016-09-19 12:58 UTC, tmcw commented
Published in v0.3.0, thanks @petttro !

2016-09-19 13:19 UTC, petttro commented
npm tests were failed.
have fixed issues: https://github.com/petttro/leaflet-image/commit/89cc04f5c4b797ac460768714157857b7fd3b718

54:6   error  Expected indentation of 4 space characters but found 5  indent
 55:9   error  Expected indentation of 9 space characters but found 8  indent
 57:9   error  Expected indentation of 9 space characters but found 8  indent
 60:5   error  Expected indentation of 5 space characters but found 4  indent
 249:10  error  Missing semicolon                                       semi